### ISSUE TITLE
Issue in compiling phylostratr results

### ISSUE THREAD

**Issue by priyanka8590** [arendsee/phylostratr#11]
After I loaded BLAST, I ran this line 
strata <- strata_blast(strata, blast_args=list(nthreads=8L)) %>% strata_besthits

It skipped a bunch of taxonomy IDs, and stopped at 3311. It gave this error: 

3311: blasting ...

sh: line 1:  7524 Segmentation fault      (core dumped) 'blastp' -db blastdb/SGTW.faa -query uniprot-seqs/3702.faa -outfmt "6 qseqid sseqid qstart qend sstart send evalue score" -num_threads 8 -seg no > '3311.tab'

Error in .validate_table(out, "read_blast", c("qseqid", "sseqid", "evalue")) : 

  'read_blast': input table is missing required columns: qseqid, sseqid, evalue

Columns:

I then looked at my .tab files and I had no tab file for 3311. I don't know what I may be doing wrong. I'm attaching my R code. Maybe it can give you some clue as to what I may be doing wrong. 

Thank you!

**Comment by arendsee** [comment]
This issue has been resolved outside github. If you have a similar problem, you can open a new issue.

**Comment by priyanka8590** [comment]
I just wanted to add a little detail which can help. Before running BLAST, when you generate all the files for BLAST to run:
echo -e 'qseqid\tsseqid\tqstart\tqend\tsstart\tsend\tevalue\tscore' > <target>.tab
blastp \
-query <focal_species> \
-db <target_database> \
-outfmt '6 qseqid sseqid qstart qend sstart send evalue score ' >> <target>.tab
This part in the supplementary file should contain as the last column 'staxid' because that column will contain the taxonomic ID in each generated BLAST file.
