### ISSUE TITLE
strata_blast issue 

### ISSUE THREAD

**Issue by CWYuan08** [arendsee/phylostratr#15]
Hi there, 
I couldn't run strata_blast(strata), and it says: 
Error in system2("blastdbcmd", stdout = TRUE, stderr = TRUE, args = c("-info",  : 
  error in running command

How can I solve the problem? 

Thank you!
Best,
CW

**Comment by arendsee** [comment]
Thanks for the report @CWYuan08 , do you have `blastdbcmd` installed on your system?

Are you on a Mac?

**Comment by CWYuan08** [comment]
@arendsee, 
thanks for prompt reply, I have just installed blast and can run blastdbcmd from the command line. But I still got the same error when I rerun the r command..what can I do next?
Yes I'm on a Mac 

Thanks
CW

**Comment by arendsee** [comment]
The error is being raised in the function `.bastdb_exists` of the `blast.R` file in the package. The purpose of this function is to confirm that a particular blast database exists. The failure indicates that it does not.

I've improved the error message. It will now tell you the path of the expected blast database. This will not fix your problem, but the new error message should tell you where to look.

Pull the latest version of phylostratr from github and rerun the analysis. I expect it will fail again. The new error message it raises should be something like this:

```
BLAST Database error: No alias or index file found for protein database [xxxxxx] in search path [/path/to/working/directory::]
```

If you get this message, there may be something wrong in your inputs or file structure.

If you don't get this error message, paste in the error message you do get and we'll go from there.

**Comment by CWYuan08** [comment]
@arendsee,
I haven't rerun the analysis, just a quick question, what databases do I need? all nr files from NCBI Blast database? 
(Sorry I am based in the UK, it is mid-night now, will rerun the analysis tomorrow.) 

Thanks
CW

**Comment by CWYuan08** [comment]
Dear @arendsee,

I have rerun and got: 
"69293.faa: making blast database ...
Building a new DB, current time: 06/12/2020 10:36:17New DB name:   /private/var/folders/k5/spztwp4x1n7_24q50wj3r0240000gn/T/RtmpA3HW6e/_blast_db/blastdb/69293.faaNew DB title:  uniprot-seqs/69293.faaSequence type: ProteinKeep MBits: TMaximum file size: 1000000000BBLAST options error: File uniprot-seqs/69293.faa does not exist
Error in (function (fastafile, blastdb = "blastdb", verbose = FALSE)  :
 Failed to make blast database blastdb/69293.faa
In addition: Warning message:
In system2("makeblastdb", stderr = TRUE, stdout = TRUE, args = c("-dbtype",  :
 running command ''makeblastdb' -dbtype prot -in uniprot-seqs/69293.faa -out blastdb/69293.faa 2>&1' had status 1

I guess this means the database is missing, how should I build the database? 
Thank you very much for your help

Best
CW

**Comment by arendsee** [comment]
You do not need to build or download a database. `phylostratr` makes the BLAST databases automatically from the protein files that are automatically downloaded from UniProt. The file 69293.faa should contain the protein sequences from the species with the NCBI taxonomy ID 69293.

The error message says that the file `uniprot-seqs/69293.faa` could not be found. `phylostratr` should have created this directory and placed the protein files in it. Is there a folder `uniprot-seqs` in your working directory? Also, what code are you running?

**Comment by CWYuan08** [comment]
Hi @arendsee,
I do have the uniprot-seqs folder with 69233.faa in it. The code I am running was strata_blast(strata, makedb_args = list(verbose = T), blast_args = list(nthreads = 3)).

Thanks 
CW

**Comment by arendsee** [comment]
Are you running this from RStudio? You need to be sure that `uniprot-seqs` is in your working directory. The error message suggests that you are in a temporary folder.

**Comment by CWYuan08** [comment]
@arendsee,
Thank you! It took some time to run the command. The command was running for a while but stopped, and I got:

1008392.faa: making blast database ...
Building a new DB, current time: 06/14/2020 11:31:39New DB name:   blastdb/1008392.faaNew DB title:  uniprot-seqs/1008392.faaSequence type: ProteinKeep MBits: TMaximum file size: 1000000000BBLAST options error: File uniprot-seqs/1008392.faa is empty
Error in (function (fastafile, blastdb = "blastdb", verbose = FALSE)  :
 Failed to make blast database blastdb/1008392.faa
In addition: Warning message:
In system2("makeblastdb", stderr = TRUE, stdout = TRUE, args = c("-dbtype",  :
 running command ''makeblastdb' -dbtype prot -in uniprot-seqs/1008392.faa -out blastdb/1008392.faa 2>&1' had status 1

I checked this file in uniprot-seqs, looks like this is the only file that is empty, what should I do?

Best,
CW

**Comment by arendsee** [comment]
Is the species 1008392 in uniprot? The files will be empty if no data is available for the species. If the proteome is available elsewhere, then you can replace the file.

**Comment by CWYuan08** [comment]
@arendsee 
I see, but I don't know where this number was from, I didn't specify it in my previous command, and I couldn't find its proteome, how could I remove it from the analysis? I tried to delete it, but it then reports that this file is absent.

Thank you
Best, 
CW

**Comment by arendsee** [comment]
The species 1008392 is one `phylostratr`'s default bacterial representatives. That particular proteome was apparently deleted when the curators removed redundant proteomes earlier this year [(see there)](https://www.uniprot.org/help/proteome_redundancy). We can fix your problem by removing this representative.

The default bacterial representatives are stored in the package data ("inst/extdata/prokaryote_sample.rda"). You can remove representatives from this selection with the following command (executed from the "inst/extdata" folder):

``` R
reps <- readRDS("prokaryote_sample.rda")
reps2 <- phylostratr::prune(reps, 1008392, type="name")
saveRDS(reps, "prokaryote_sample.rda")
```

Then reinstall the package with `devtools::install()`.

I've explained the process here for future reference, but I'll push the updated selections to github and you can just reinstall `phylostratr` and it should work.

**Comment by arendsee** [comment]
I closed the issue with the last commit. If you have any more issues you can reopen it. Also, you can message if all goes well. It is nice for me to know.

**Comment by CWYuan08** [comment]
@arendsee, 
Hi, I reinstalled then it was running for two days however, it stopped again and said:" BLAST Database error: No alias or index file found for protein database [blastdb/1008392.faa] in search path [/Users/CW::] 
And it reported again what said above "File uniprot-seqs/1008392.faa does not exist"

Sorry, I am not sure if I followed your instruction. How can I access the package data in R? It keeps saying no such file or directory..
I then just downloaded the file from GitHub and run the commands you put above, and got 
"Error in clean_phyid(x, id, type = type) :
 Could not find nodes with requested names" 

Could you please tell me what I have done wrong? 
Thank you for your patience!

Best 
CW

**Comment by arendsee** [comment]
Can you print your session info information? Do the following and tell me what it says:

``` R
library(phylostratr)
library(devtools)
session_info()
```

The session info output should have the exact line:

```
 phylostratr * 0.2.1   2020-06-18 [1] Github (arendsee/phylostratr@dc1e49a)
```

If not, then you have the wrong phylostratr version and need to reinstall with `devtools::install_github("arendsee/phylostratr")`.

Next do the following:

```
d=readRDS(system.file("extdata", "prokaryote_sample.rda", package="phylostratr"))
d$tip.labels
```

The above command will list all the strains representing bacteria. If 1008392 is in the list, then you probably have the wrong phylostratr version. Otherwise, you likely have something messed up in your working directory. You might need to delete the old 1008392 files. Did you start the rerun from a fresh R session?

**Comment by CWYuan08** [comment]
@arendsee,
Thanks! 
I do have  "phylostratr * 0.2.1   2020-06-18 [1] Github (arendsee/phylostratr@dc1e49a)" installed, and 1008392 is not in the list. 
I thought I restarted Rstudios, but I will try it again with a fresh R session and get back to you.  

Thank you for your patience!

Best
CW

**Comment by arendsee** [comment]
Before you rerun it, you should go to your working directory and delete the 1008392 files in uniprot-seqs and the blast output files (if it appears in either place).

Oh, and you don't need to download "prokaryote_sample.rda" or do anything else.

**Comment by CWYuan08** [comment]
Dear @arendsee, 

sorry to bother again, I seem to encounter the same issue again
I am getting the same issue:

Error in system2("blastdbcmd", stdout = TRUE, stderr = TRUE, args = c("-info",  : 
  error in running command

I have phylostratr 0.2.1 and have installed blast too. 
any help would be greatly appreciated!!  

Many thanks!
Best
CW
