### ISSUE TITLE
[Question]NCBI nr database VS uniprot 

### ISSUE THREAD

**Issue by haojingshao** [arendsee/phylostratr#16]
Hi arendsee,
The first paper "Domazet-Loso et al. 2007" uses NCBI nr database. Your R code indicates that phylostratr uses Uniprot. I find the classification results from two databases are very different. I am new to prot database. Do you know what is the difference between them? Why does phylostratr use uniprot?

Thanks,
Haojing

**Comment by arendsee** [comment]
Hi Haojing,

`phylostratr`'s approach is to search a select set of complete proteomes rather than everything in the huge nr database. The `phylostratr` [paper](https://academic.oup.com/bioinformatics/article/35/19/3617/5380767) details the reasoning.

Zeb
