### ISSUE TITLE
Error: 'classification' is not an exported object from 'namespace:taxizedb'

### ISSUE THREAD

**Issue by paolacornejo** [arendsee/phylostratr#19]
Hello, 

I am trying to use phylostratr and I cannot even run the example. When I run the function "uniprot_strata" I get the following error:

Error: 'classification' is not an exported object from 'namespace:taxizedb'

I looked at the function (uniprot_strata) and it seems it calles the function "taxizedb::classification" but this function is not part of the package    taxizedb:

 `lsf.str("package:taxizedb")`
db_download_col : function (verbose = TRUE)  
db_download_gbif : function (verbose = TRUE)  
db_download_itis : function (verbose = TRUE)  
db_download_tpl : function (verbose = TRUE)  
db_load_col : function (path, user = "root", pwd = NULL, verbose = TRUE)  
db_load_gbif : function (verbose = TRUE)  
db_load_itis : function (path, user, pwd = NULL, verbose = TRUE)  
db_load_tpl : function (path, user, pwd = NULL, verbose = TRUE)  
sql_collect : function (src, query, ...)  
src_col : function (user = "root", password = NULL, dbname = "col", ...)  
src_gbif : function (path)  
src_itis : function (user, password, dbname = "ITIS", ...)  
src_tpl : function (user, password, dbname = "plantlist", ...)

The following are the versions of packages loaded:
 [1] testthat_2.3.2    onekp_0.3.0       rlang_0.4.7       taxize_0.9.97    
 [5] magrittr_1.5      phylostratr_0.2.1 readr_1.3.1       dplyr_1.0.1      
 [9] taxizedb_0.1.4    hoardr_0.5.2      reshape2_1.4.4    withr_2.2.0      
[13] devtools_2.3.0    usethis_1.6.1    

I am using a wrong version of any package?

**Comment by arendsee** [comment]
Classification is definitely in the taxizedb package. Try pulling the latest version from github: `devtools::install_github("ropensci/taxizedb")`.
