### ISSUE TITLE
Installation issue: phylostratr is fully compatible only with latest ggtree and treeio

### ISSUE THREAD

**Issue by urmi-21** [arendsee/phylostratr#2]
Phylostratr is fully compatible only with latest ggtree (1.11.5) and treeio (>=1.3.9). During installation of phylostratr with `devtools::install_github(arendsee/phylostratr)` it installs treeio v1.2.1 from bioconductor which in turn makes ggtree fail to install. Can you change installation of treeio and ggtree directly from github ?

**Comment by arendsee** [comment]
The `phylostratr` DESCRIPTION file already states a dependency on the github variant of `ggtree` (version >= 1.11.2), and this version works in my tests. `treeio` is not used directly by `phylostratr`, but is probably imported when `ggtree` is installed. The latest github version of `ggtree` does state the dependency treeio >= 1.3.9.

Everything ought to work. You might tree uninstalling `ggtree`, `treeio`, and `phylostratr` and then installing `phylostratr`. Let the package manager figure out what to install and everything should be fine.

Tell me how this goes.

**Comment by urmi-21** [comment]
Thats what i did let the package manager install it. But then my ggtree installation failed as treeio v1.2.1 as installed by the package manager. So I had to manually install both from github and then i installed phylostratr, which worked!
My R version is 3.4.3

**Comment by arendsee** [comment]
I've reported an issue at `ggtree`: GuangchuangYu/ggtree#168

Once this is updated on the `ggtree` side, installation should be fine. For now, you can install as so:

```R
install_github('GuangchuangYu/treeio')
install_github('arendsee/phylostratr')
```

**Comment by arendsee** [comment]
`ggtree` is now updated, so everything should work
