### ISSUE TITLE
Possible bug? number of genes per strata is way higher than the total number of genes

### ISSUE THREAD

**Issue by aseetharam** [arendsee/phylostratr#4]
I re-ran the `phylostratr` recently on `Apis florea` and got really weired results. The number of genes reported per strata were way higher than the previous run and the sum doesn't equate to the total number of genes. I think it is due to some bug introduced recently because the previous run had much resonable numbers. The only difference between the previous run and this run is that I've added 16 extra spp for the latest run. 

Here is more information:

### R script for previous run

```
library(devtools)
source("https://bioconductor.org/biocLite.R")
library(phylostratr)
library(magrittr)
library(plotly)
focal_taxid <- '7463'
strata <-
  uniprot_strata(focal_taxid, from=2) %>%
  add_taxa('7463') %>%
  strata_apply(f=diverse_subtree, n=5, weights=uniprot_weight_by_ref()) %>%
  use_recommended_prokaryotes %>%
  uniprot_fill_strata
results <- strata_blast(strata, blast_args=list(nthreads=8)) %>%
  strata_besthits %>%
  merge_besthits
phylostrata <- stratify(results)
write.csv(phylostrata, "phylostrata_table.csv")
tabled <- table(stratify(results)$mrca_name)
write.csv(tabled, "phylostrata_stats.csv")
```
### R script for the present run:

```
#!/usr/bin/Rscript
library(devtools)
source("https://bioconductor.org/biocLite.R")
library(phylostratr)
library(magrittr)
library(plotly)
focal_taxid <- '7463'
strata <-
  uniprot_strata(focal_taxid, from=2) %>%
  add_taxa('7463') %>%
  strata_apply(f=diverse_subtree, n=5, weights=uniprot_weight_by_ref()) %>%
  add_taxa(c('30195','88501','78185','78189','44477','132113','143995','156304','166423','175324','175328','178035','481568','516756','597456')) %>%
  use_recommended_prokaryotes %>%
  uniprot_fill_strata
results <- strata_blast(strata, blast_args=list(nthreads=8)) %>%
  strata_besthits %>%
  merge_besthits
phylostrata <- stratify(results)
write.csv(phylostrata, "phylostrata_table.csv")
tabled <- table(stratify(results)$mrca_name)
write.csv(tabled, "phylostrata_stats.csv")
plot_heatmaps(results, "heatmaps3.pdf")
```

### Previous results:
```
"","Var1","Freq"
"1","cellular organisms",6853
"2","Eukaryota",5120
"3","Opisthokonta",415
"4","Metazoa",1940
"5","Eumetazoa",333
"6","Bilateria",456
"7","Protostomia",277
"8","Ecdysozoa",62
"9","Panarthropoda",48
"10","Arthropoda",216
"11","Mandibulata",72
"12","Pancrustacea",131
"13","Hexapoda",112
"14","Neoptera",639
"15","Holometabola",62
"16","Apocrita",305
"17","Aculeata",188
"18","Apoidea",75
"19","Apidae",70
"20","Apis",97
"21","Apis florea",205
```

### Present results:

```
"","Var1","Freq"
"1","cellular organisms",284161
"2","Eukaryota",103882
"3","Opisthokonta",44785
"4","Metazoa",63526
"5","Eumetazoa",63633
"6","Bilateria",130111
"7","Protostomia",153915
"8","Ecdysozoa",173269
"9","Panarthropoda",37748
"10","Arthropoda",95879
"11","Mandibulata",14997
"12","Pancrustacea",57473
"13","Hexapoda",48852
"14","Neoptera",106423
"15","Holometabola",116966
"16","Apocrita",33352
"17","Aculeata",72995
"18","Apoidea",38565
"19","Apidae",158736
"20","Apinae",8673
"21","Apis",15274
"22","Apis florea",15810
```

Clearly, this isn't right. Could you please take a look at it?

Thanks!

**Comment by arendsee** [comment]
@aseetharam Could you send me the head of one of you BLAST files?

**Comment by aseetharam** [comment]
Sure!
```
$ head 6669.tab
qseqid	sseqid	qstart	qend	sstart	send	evalue	score	staxid
sp|E9HCD7|NNRE_DAPPU	Apiflo_255	29	227	1	205	9.22e-71	544	6669
sp|E9HCD7|NNRE_DAPPU	Apiflo_5888	70	151	63	131	2.1	62	6669
sp|E9HCD7|NNRE_DAPPU	Apiflo_4646	89	108	501	520	2.3	62	6669
sp|E9HCD7|NNRE_DAPPU	Apiflo_2965	17	94	266	342	2.7	61	6669
sp|E9HCD7|NNRE_DAPPU	Apiflo_8041	190	226	227	267	2.9	61	6669
sp|E9HCD7|NNRE_DAPPU	Apiflo_15515	123	145	32	54	3.5	58	6669
sp|E9HCD7|NNRE_DAPPU	Apiflo_3565	31	56	17	42	4.0	60	6669
sp|E9HCD7|NNRE_DAPPU	Apiflo_3991	25	46	654	675	5.5	59	6669
sp|E9GD30|SIR5_DAPPU	Apiflo_9132	11	272	4	265	4.48e-121	886	6669
```
I just picked a random one. Let me know if you need something specific.

Thanks,

**Comment by arendsee** [comment]
@arun Do you happen to know the phylostratr version for you old run?

**Comment by aseetharam** [comment]
Sorry, I don't have that info. But the files were created on Jan 29th, if that is of any help (and you probably fixed some of the issues that I was having that day so, I was running the latest version as of Jan 29th)!

**Comment by arendsee** [comment]
That narrows it down, thanks

**Comment by arendsee** [comment]
@aseetharam Thanks, narrows it down.

**Comment by arendsee** [comment]
Weird, I am still getting the correct results on the yeast dataset.

**Comment by aseetharam** [comment]
Do you want the dataset I'm working on? I've no luck getting the right results still :(

**Comment by arendsee** [comment]
Probably I don't need the whole data. How about you upload the file made from this code:

```R
saveRDS(head(results, 10000), file="results-head.Rda")
```

**Comment by arendsee** [comment]
@aseetharam Could you post the data? I forgot to tag you in the last message.

**Comment by aseetharam** [comment]
oops, here it is!
[results-head.zip](https://github.com/arendsee/phylostratr/files/1981776/results-head.zip)
(file is zipped)

**Comment by arendsee** [comment]
@aseetharam OK, I may have fixed it, try it again

**Comment by arendsee** [comment]
@aseetharam Well, at least I did fix a bug. Though I think the one I fixed may not be the one that was causing the problem.

**Comment by arendsee** [comment]
@aseetharam Sorry, disregard the last two messages, I didn't fix a bug, I added a new one.

**Comment by aseetharam** [comment]
Thanks for all the updates! Hope it gets fixed soon 👍

**Comment by arendsee** [comment]
This is a bit strange, can I get another file from you:

```R
saveRDS(results[grepl("WZ", results$qseqid), ], file="results-WZ.Rda")
```

**Comment by aseetharam** [comment]
Here it is!
[results-WZ.Rda.gz](https://github.com/arendsee/phylostratr/files/1984901/results-WZ.Rda.gz)
Thanks,

**Comment by arendsee** [comment]
@aseetharam Did we ever resolve this?

**Comment by aseetharam** [comment]
Not sure if we resolved it, but I found out that it only happens when extra taxa is added that are sister spp to the focal taxa id. This made sense to me so I did not bug you further!

**Comment by arendsee** [comment]
Hmm, `phylostratr` ought to be able to handle subspecies. I'll close this for now. When I have time, I'll look into subspecies cases and if I can isolate the bug, then I'll open a general issue report.

Thanks @aseetharam !
