### ISSUE TITLE
How much local storage does it normally take?

### ISSUE THREAD

**Issue by yenagra** [arendsee/phylostratr#5]
Just wonder if I need to enlarge my harddrive before running this program.

**Comment by arendsee** [comment]
@yenagra I wouldn't worry about the harddrive. `phylostratr` only uses proteomes and these tend to only require tens of megabytes. So as long as you have a few free GB, you will be fine.

You are far more likely to run into memory problems. I can just barely run *Arabidopsis thaliana* test case on my desktop, where I have 8 GB of RAM. So currently you may need to run `phylostratr` on a server if you are doing a large study.

There is certainly a lot of room for improvement in the `phylostratr` implementation. I could replace the in-memory data structures with a SQLite database. That would basically solve the memory problem.

The other performance issue to consider is the time required to BLAST everything. You will likely want to run the BLASTs on a server and `phylostratr` currently doesn't automate this. Though handling high-performance computation in R is totally possible.

**Comment by yenagra** [comment]
That's good, thanks.
