### ISSUE TITLE
Cannot resolve tree ids in `merge_besthits`

### ISSUE THREAD

**Issue by palfalvi** [arendsee/phylostratr#6]
Hi,

Thank you for the package and the framework, it is really great!

I met with a small issue while running `merge_desthits()` on some new data:

```
Error in clean_phyid(x, id, type = type) : 
  Cannot automatically resolve tree id.It could be either a phylo object index or a taxon name.Please specify the type.
Calls: merge_besthits ... clean_phyid -> parent -> parent.phylo -> clean_phyid
Execution halted
```
As I am working with unpublished data, I added several ids and fasta files manually. It caused no problem for the blast or plotting the tree. I do not know if it is connected here either, but mentioning. Every other steps, I followed your tutorials. 
Also, i installed the newest versions of required packages (treeio, ggtree).

Thank you for the answers in advance!

**Comment by arendsee** [comment]
Hi @palfalvi, thanks for the report!

This error message is raised when `phylostratr` can't tell whether a node or leaf label in the tree is an index (ranging from 1 to the number of nodes+leaves in the tree) or a name. 

The error occured in the command `merge_besthits(x)`. What does `leafs(x)` tell you? The problem might be that you have a mix of species names and taxonomy IDs.

**Edited to replace an earlier bad answer**

**Comment by palfalvi** [comment]
Thanks. `leafs(x)` gives back a vector with the ncbi species IDs (only numeric, no name).

**Comment by arendsee** [comment]
Could you give me the list of ncbi species IDs? I basically know where this bug is occurring and I think I'm just missing some edge case. If I have the list of species I can isolate the problem and make a test case for it.

As a hack, you can convert the species IDs to species names:
```
strata_obj <- strata_convert(strata_obj, target="all", to="name")
```
And then rerun `merge_besthits`. This *should* work.

**Comment by palfalvi** [comment]
c("4362", "16681", "3343", "63099", "231682", "3381", "45172", 
"307728", "63459", "3311", "13805", "4932", "9606", "1194090", 
"1797576", "572547", "906968", "667014", "653733", "522772", 
"1184387", "638303", "445932", "1408204", "515635", "511051", 
"981222", "234267", "401053", "1325564", "469616", "1805218", 
"1703384", "1797384", "314345", "857265", "1797220", "1945860", 
"1628278", "441768", "1895832", "1262851", "266117", "1121877", 
"1003195", "872965", "926550", "1805232", "1703396", "360412", 
"479434", "357808", "661478", "1303518", "937777", "573058", 
"1555112", "888062", "1917462", "1262887", "617121", "1956166", 
"1008392", "1313304", "1896212", "313628", "1437425", "1142394", 
"1387353", "1307763", "481448", "1262865", "320771", "497964", 
"199", "48", "1183438", "1798435", "377431", "1524460", "634771", 
"1660162", "242619", "525373", "1945862", "1803813", "1775755", 
"351160", "190192", "387631", "186497", "1495144", "797303", 
"419665", "187420", "1903181", "1237085", "1365176", "37360", 
"9598", "5786", "44415", "5671", "611791", "1460289", "280699", 
"70448", "41875", "564608", "574566", "3076", "1157962", "33097", 
"145388", "3218", "3197", "88036", "13333", "39946", "4555", 
"4615", "214687", "42345", "906689", "1088818", "29655", "56857", 
"218851", "4432", "35608", "4113", "4155", "1590841", "3702", 
"2094558", "57577", "29760", "3562")

**Comment by palfalvi** [comment]
Thanks, the `convert_strata` tricked worked.

**Comment by arendsee** [comment]
Thanks! I'll look into this.

**Comment by arendsee** [comment]
What is your focal species?

**Comment by palfalvi** [comment]
16681

**Comment by arendsee** [comment]
Oooh fun, a carnivore

**Comment by arendsee** [comment]
OK, I can replicate the problem now:

```R
# build a tree where `taxids` is your list of NCBI taxonomy IDs
tree <- phylostratr::lineages_to_phylo(taxizedb::classification(taxids))
# make a Strata object around your focal species
strata_obj <- phylostratr::Strata(focal_species=16681, tree)
# map the identity function over all cousin branches in your tree
# (branches from the nodes between the focal species and the root)
phylostratr::strata_map(strata_obj, identity)
```

`strata_map` is called by `merge_besthits`.

Anyway, I'm getting closer now.

**Comment by arendsee** [comment]
Odd, so if you take out the Venus Flytrap (4362), the bug goes away ...

**Comment by palfalvi** [comment]
Thanks for looking into it. 
That is indeed strange. Especially if I want to use that as my next focal species. I will check tomorrow if that is working with this or not.

**Comment by arendsee** [comment]
OK, good night. I'll find the bug.

**Comment by arendsee** [comment]
Here is a minimal example:

```R
taxids=c("4362", "16681", "1194090", "1142394")
tree <- phylostratr::lineages_to_phylo(taxizedb::classification(taxids))
strata_obj <- phylostratr::Strata(focal_species=16681, tree)
phylostratr::strata_map(strata_obj, identity)
```

**Comment by arendsee** [comment]
Everything *should* be awesome now! Thanks for the report and feel free to message if you run into any more problems. Also feel free to write reports for anything that is poorly documented or just weird.
