### ISSUE TITLE
swap `BiocInstaller` with `BiocManager`

### ISSUE THREAD

**Issue by aseetharam** [arendsee/phylostratr#9]
Looks like package `BiocInstaller` is not available (for R version 3.5.0) and it is superseded by `BiocManager`. Can this be changed so that the installer finds BiocManager and does not complain?

```
> install_github("arendsee/phylostratr")
Downloading GitHub repo arendsee/phylostratr@master
from URL https://api.github.com/repos/arendsee/phylostratr/zipball/master
Installing phylostratr
‘BiocInstaller’ must be installed for this functionality.
Would you like to install it?

1: Yes
2: No

Selection: 1
Installing package into ‘/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/r-rsqlite-2.0-zew7f5pkhdh6gk4qdv6hown4uf4zszsb/rlib/R/library’
(as ‘lib’ is unspecified)
Warning in install.packages(pkg) :
  'lib = "/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/r-rsqlite-2.0-zew7f5pkhdh6gk4qdv6hown4uf4zszsb/rlib/R/library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) yes
Error in loadNamespace(name) : there is no package called ‘BiocInstaller’
In addition: Warning message:
package ‘BiocInstaller’ is not available (for R version 3.5.0)
```

Thanks,

**Comment by arendsee** [comment]
This is actually an issue in `devtools`. You can get around it by manually installing `Biostrings` (the one Bioconductor package `phylostratr` uses).

```R
install.packages("BiocManager")
BiocManager::install("Biostrings")
```

**Comment by aseetharam** [comment]
No, that doesn't work for me. I installed it and loaded it, but it still goes through the same steps asking me to install `BiocInstaller`  Not sure what to do.

**Comment by arendsee** [comment]
Is your devtools package up-to-date?

**Comment by aseetharam** [comment]
Hi Zeb,

Here is my session info:
```
Packages -----------------------------------------------------------------------
 package      * version date       source
 BiocGenerics * 0.28.0  2018-10-30 Bioconductor
 BiocManager    1.30.4  2018-11-13 CRAN (R 3.5.0)
 Biostrings   * 2.50.2  2019-01-03 Bioconductor
 curl           3.0     2017-10-06 CRAN (R 3.5.0)
 devtools     * 1.12.0  2016-12-05 CRAN (R 3.5.0)
 digest         0.6.12  2017-01-27 CRAN (R 3.5.0)
 git2r          0.18.0  2017-01-01 CRAN (R 3.5.0)
 httr           1.3.1   2017-08-20 CRAN (R 3.5.0)
 IRanges      * 2.16.0  2018-10-30 Bioconductor
 memoise        1.1.0   2017-04-21 CRAN (R 3.5.0)
 R6             2.2.2   2017-06-17 CRAN (R 3.5.0)
 S4Vectors    * 0.20.1  2018-11-09 Bioconductor
 withr          1.0.2   2016-06-20 CRAN (R 3.5.0)
 XVector      * 0.22.0  2018-10-30 Bioconductor
 zlibbioc       1.28.0  2018-10-30 Bioconductor
```
Thanks,

**Comment by arendsee** [comment]
Yeah, that is pretty old, you might want to upgrade it. The current `devtools` package should be using the up-to-date function. I'm using version 2.0.1.

**Comment by aseetharam** [comment]
Thanks, that helped! I'll close this issue now.
BTW, the `taxizedb` have additional dependencies and are really pain to install them on a cluster (sqlite/postgresql).

**Comment by arendsee** [comment]
Ah yeah, true about the taxizedb dependencies. sqlite is needed to hand the SQL database. But the other tricky dependencies are not. The taxizedb dependencies could probably be made optional. I'll see what I can do.

**Comment by arendsee** [comment]
@aseetharam Actually, I ran into the same dependency problem earlier. I solved it by modifying the `taxizedb` package, removing the need for the missing dependencies -- specifically RMariaDB and RPostgreSQL. You can install that version from arendsee/taxizedb. This is not a good long-term solution, though, since I am not maintaining that package.
